import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home({ memories = {} }) {
  return (
    <div className={styles.container}>
      <Head>
        <title>NextJS Graphql Contentful</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <h1 className={styles.title}>
          NextJS Graphql Contentful
        </h1>
       <pre>{JSON.stringify(memories, null, 2)}</pre>
      </main>
    </div>
  )
}

// export async function getStaticProps() {
//   const result = await fetch(
//     `https://graphql.contentful.com/content/v1/spaces/${process.env.CONTENTFUL_SPACE_ID}/environments/master`,
//     {
//       method: 'POST',
//       headers: {
//         Authorization: `Bearer ${process.env.CONTENTFUL_DELIVERY_TOKEN}`,
//         'Content-Type': 'application/json',
//       },
//       body: JSON.stringify({
//         query: `
//           query {
//             memoryCollection {
//               items {
//                 title
//                 slug
//                 description
//               }
//             }
//           }
//         `,
//       }),
//     },
//   );

//   if (!result.ok) {
//     console.error(result);
//     return {};
//   }

//   const { data } = await result.json();
//   const memories = data.memoryCollection.items;

//   return {
//     props: {
//       memories,
//     },
//   };
// }

export async function getStaticProps() {

  const result = await fetch('https://graphql.contentful.com/content/v1/spaces/su0c72xtlnn3/environments/master', {
    method: 'POST',
    headers: {
      Authorization: 'Bearer NnbMFw8hCX8kXswoYMMY8snicg_SeGBDGAT5smqsVNk',
      'Content-Type': 'application/json'
    },
    body: JSON.stringify({
      query: `
      
      query {
        memoryCollection {
          items {
            title
            description
            slug
          }
        }
      }

        `
    })
  });

  if (!result.ok) {
    console.log(result);
    return {};
  }

  const { data } = await result.json();
  const memories = data.memoryCollection.items;

  return {
    props: {
      memories
    }
  }
}



